on: push
name: GitHub Actions Continuous Integration
jobs:
  phpunit:
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.2
 
    services:
      mysql:
        image: mysql:8.1.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_DATABASE: test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
 
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
 
    - name: Install composer dependencies
      run: |
        composer install --no-scripts
      working-directory: repository/laravel
 
    - name: Prepare Laravel Application
      run: |
        cp .env.ci .env
        php artisan key:generate
      working-directory: repository/laravel
 
    - name: Run Testsuite
      run: vendor/bin/phpunit tests/
      working-directory: repository/laravel

    - name: Run Phpstan
      run: vendor/bin/phpstan analyse
      working-directory: repository/laravel
