on: push
name: GitHub Actions Continuous Integration
jobs:
  laravel:
    name: Laravel CI Pipeline
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: repository/laravel
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.2
 
    services:
      mysql:
        image: mysql:8.1.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_DATABASE: test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
 
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
 
    - name: Install composer dependencies
      run: |
        composer install --no-scripts
 
    - name: Prepare Laravel Application
      run: |
        cp .env.ci .env
        php artisan key:generate

    - name: Run Migrations
      run: |
        php artisan migrate --no-interaction --ansi
 
    - name: Run Testsuite
      run: php artisan test --ansi

    - name: Run Phpstan
      run: vendor/bin/phpstan analyse

    - name: Run PHP Insights
      run: |
        php artisan insights --no-interaction --ansi --format=github-action
